version: '3.8'
services:
  mysqldb:
    container_name: db
    image: mysql:8.0
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
    expose:
      - $MYSQLDB_LOCAL_PORT
  app:
    depends_on:
      - mysqldb
    build: .
    env_file: .env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    stdin_open: true
    tty: true
    volumes:
      - ./worker/:/worker/
      - /worker/node_modules
volumes: 
  db:
  node_modules: