tools:
  exceptions: ""
  logging: ""
  ci: ""

services:
  production: ""

docs:
  frontend: "https://github.com/dcsil/konsensus-app-frontend"
  backend: "https://github.com/dcsil/konsensus-app-backend"

commands:
  bootstrap: "./script/bootstrap"
  database: "mysql.server start"  # edit the MYSQLDB variables in the .env file
  server: "npm start"
  test: "jest"