orbs: # declare what orbs we are going to use
  node: circleci/node@5.0.0 # the node orb provides common node-related configuration

version: 2.1 # using 2.1 provides access to orbs and other features

jobs:
  setup:
    parameters:
        mysql_root_password:
          type: string
          default: 123
        mysql_database:
          type: string
          default: konsensus-app-backend
    docker:
      - image: 'cimg/base:stable'
      - image: cimg/mysql:8.0
        environment:
          MYSQL_ROOT_PASSWORD: parameters.mysql_root_password
          MYSQL_DATABASE: parameters.mysql_database

    steps:
      - checkout
      - node/install:
          install-yarn: false
          node-version: '16.14'
      - run: node --version
      - run:
          name: Wait for Database Connection
          # preinstalled in circleci/* docker image
          command: dockerize -wait tcp://localhost:3306 -timeout 1m
      - run: npm install
      - run: npm test

workflows:
  test_backend:
    jobs:
      - setup
      # - node/test:
      #     test-results-for: jest
      #     requires: [setup]
