#!/bin/sh

# script/bootstrap: Resolve all dependencies that the application requires to
#                   run.

# Exit immediately if a command exits with a non-zero status.
set -e

# Install Homebrew
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

# Install dependencies from Brewfile
PATH="$PATH:node_modules/.bin"

cd "$(dirname "$0")/.."

if [ "$(uname -s)" = "Darwin" ]; then
  brew bundle check >/dev/null 2>&1  || {
    echo "==> Installing Homebrew dependencies…"
    brew bundle
  }
fi

# Install dependencies from npm
echo "==> Installing npm dependencies…"
npm install